# ===================================================================
# Spring Boot configuration for the "cloudfoundry" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
    port: 8080
eureka:
    instance:
        prefer-ip-address: false
#        hostname: ${vcap.application.uris[0]}
#        nonSecurePort: 80
logging:
    level:
        com.bmcd.asset.health.uaa: DEBUG
        io.github.jhipster: DEBUG
spring:
    data:
        jest:
             uri: https://cloudfoundry:ab9d4b19be507c6797ce962f4f991750@thorin-us-east-1.searchly.com
liquibase:
        contexts: demo
